<?php

/*********************************************************************
* Extension configuration file for ext "quick_form".
*
* Generated by ext 25-07-2013 10:46 UTC
*
* https://github.com/t3elmar/Ext
*********************************************************************/

$EM_CONF[$_EXTKEY] = array (
  'title' => 'Web Service to fetch data',
  'description' => 'Web Service to fetch data in a flexible way. Possible output format: JSON, Atom, HTML. The Web Service is meant for retrieving data only.',
  'category' => 'fe',
  'author' => 'Fabien Udriot',
  'author_email' => 'fabien.udriot@typo3.org',
  'state' => 'beta',
  'uploadfolder' => '0',
  'createDirs' => '',
  'clearCacheOnLoad' => 0,
  'version' => '0.1.0',
  'constraints' =>
  array (
    'depends' =>
    array (
      'typo3' => '6.2.0-6.2.99',
      'vidi' => '',
    ),
    'conflicts' =>
    array (
    ),
    'suggests' =>
    array (
    ),
  ),
  'user' => 'fab1en',
  'comment' => '',
);

?>